version: '3.4'

services:
  db:
    container_name: PostgreSQL
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QwErTy135790
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  profile-api:
    image: ${DOCKER_REGISTRY-}profileapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18006:80